# Generated by Django 5.2.9 on 2025-12-15 23:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("agendamento_criado", "Agendamento Criado"),
                            ("agendamento_lembrete", "Lembrete de Agendamento"),
                            ("financeiro_vencimento", "Vencimento Financeiro"),
                            ("financeiro_vencido", "Financeiro Vencido"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                ("lida", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("agendamento_id", models.UUIDField(blank=True, null=True)),
                ("financeiro_id", models.UUIDField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "lida"],
                        name="notificacoe_usuario_a5894e_idx",
                    ),
                    models.Index(
                        fields=["criado_em"], name="notificacoe_criado__1187e8_idx"
                    ),
                ],
            },
        ),
    ]
