# Generated by Django 6.0 on 2025-12-15 22:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("endereco", models.TextField(blank=True)),
                (
                    "tipo_piscina",
                    models.CharField(
                        choices=[
                            ("residencial", "Residencial"),
                            ("comercial", "Comercial"),
                        ],
                        default="residencial",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["usuario", "ativo"],
                        name="clientes_cl_usuario_759dee_idx",
                    ),
                    models.Index(fields=["nome"], name="clientes_cl_nome_b2cdde_idx"),
                ],
            },
        ),
    ]
