# Generated by Django 6.0 on 2025-12-15 22:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Financeiro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("servico", "Serviço"),
                            ("produto", "Produto"),
                            ("multa", "Multa"),
                            ("outro", "Outro"),
                        ],
                        default="servico",
                        max_length=15,
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("pago", "Pago")],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "agendamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financeiros",
                        to="agendamentos.agendamento",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financeiros",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financeiros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["data_vencimento"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "ativo"],
                        name="financeiro__usuario_141e6d_idx",
                    ),
                    models.Index(
                        fields=["cliente", "ativo"],
                        name="financeiro__cliente_cde846_idx",
                    ),
                    models.Index(
                        fields=["agendamento", "ativo"],
                        name="financeiro__agendam_961898_idx",
                    ),
                    models.Index(
                        fields=["status", "data_vencimento"],
                        name="financeiro__status_2d028e_idx",
                    ),
                ],
            },
        ),
    ]
