# Generated by Django 6.0 on 2025-12-15 22:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmado", "Confirmado"),
                            ("cancelado", "Cancelado"),
                            ("realizado", "Realizado"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["data_hora"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "ativo"],
                        name="agendamento_usuario_3225d9_idx",
                    ),
                    models.Index(
                        fields=["cliente", "ativo"],
                        name="agendamento_cliente_0c8bcf_idx",
                    ),
                    models.Index(
                        fields=["data_hora", "status"],
                        name="agendamento_data_ho_fb44eb_idx",
                    ),
                ],
            },
        ),
    ]
